config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome', as: 'welcome'
  get '/about' => 'static_pages#about', as: 'about'
  get 'contact' =>'static_pages#contact', as: 'contact'
  get '/signin' => 'sessions#new', as: 'signin'
  post '/login' => 'sessions#login'
  delete '/signout' => 'sessions#destroy'

  resources :items, only: [:index, :show]

  resources :users, only: [:new, :show, :create]
  resources :kits do
      resources :items, only: [:new, :create, :edit, :update, :destroy]
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_many :kits, through: :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :kit
  belongs_to :category
  validates :name, presence: true

  def self.by_category(category_id)
    where(category: category_id)
  end

  def self.by_rating(rating)
    where(rating: rating)
  end

  def self.highest_rated
    where(rating:  5)
  end
end

app/models/kit.rb
class Kit < ApplicationRecord
  has_many :items, dependent: :destroy
  belongs_to :user
  has_many :categories, through: :items

  validates :name, presence: true

  def items_attributes=(items_attributes)
    items_attributes.each do |i, item_attributes|
      self.items.build(item_attributes)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :kits
  has_many :items, through: :kits
  has_many :rate_comments

  validates :email, presence: true, uniqueness: true
  validates_format_of :email, :with => /\A[^@,\s]+@[^@,\s]+\.[^@,\s]+\z/
  validates :password, presence: true, length: {minimum: 6}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :is_logged_in?, :authenticate_user!

private
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

  def is_logged_in?
    !!current_user
  end

  def authenticate_user!
    redirect_to welcome_path if !is_logged_in?
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.all
      @items = Item.all
      respond_to do |format|
        format.json {render json: @items}
        format.html {render :index}
    end
  end

  def new
    @categories = Category.all
    @kit = Kit.find(params[:kit_id])
    @item = Item.new
  end

  def edit
    @categories = Category.all
    @kit = Kit.find(params[:kit_id])
    @item = Item.find(params[:id])
  end

  def create
    @categories = Category.all
    @kit = Kit.find(params[:kit_id])
    @item = @kit.items.build(item_params)
    if @item.valid?
      @item.save
      respond_to do |format|
        format.html { redirect_to kit_path(@kit) }
        format.json { render json: @item}
        end
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    respond_to do |format|
      format.html { redirect_to kit_path(@kit) }
      format.json { render json: @item}
    end
  end

  def update
    @kit = Kit.find(params[:kit_id])
    @item = Item.find(params[:id])
    @item.update(item_params)
      if @item.save
        redirect_to kit_path(@kit)
      else
        render :edit
      end
  end

  def destroy
    @kit = Kit.find(params[:kit_id])
    Item.find(params[:id]).destroy
    redirect_to kit_path(@kit)
  end

  private

  def item_params
    params.require(:item).permit(:id, :name, :brand, :color, :price, :color, :rating, :comment, :kit_id, :category_id,)
  end
end

app/controllers/kits_controller.rb
class KitsController < ApplicationController
 before_action :authenticate_user!

  def index
    @categories = Category.all
    @kits = current_user.kits
    @items = Item.all
  end

  def new
    @categories = Category.all
    @kit = current_user.kits.build
    @kit.items.build
  end

  def create
    @categories = Category.all
    @kit = current_user.kits.build(kit_params)
    if @kit.save
      redirect_to kits_path
    else
      render :new
    end
  end

  def show
    @kits = current_user.kits
    @kit = current_user.kits.find(params[:id])
    @item = Item.new
    @categories = Category.all
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @kit, status: 200 }
    end
  end

  def edit
    @kit = Kit.find_by(params[:id])
  end

  def update
    @kit = Kit.find(params[:id])
    if @kit.update_attributes(kit_params)
      redirect_to @kit
    else
      render :edits
    end
  end

  def destroy
    @kit = current_user.kits.find(params[:id])
    @kit.destroy
    redirect_to kits_path(current_user)
  end

private
  def kit_params
    params.require(:kit).permit(:id, :name, :description, :user_id, :items_attributes => [:id, :name, :brand, :color, :price, :rating, :comment, :category_id, :_destroy])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def welcome
  end

  def new
  end

  def login
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to kits_path(@user)
    else
      flash.now[:error] = "Invalid username/password"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to welcome_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to kits_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/items/_form.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@item.errors.count, "error") %>.
      Please fix and submit again.
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div>
  <%= form_for [@kit, @item], :html => { :class => "new_item" } do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br>
  <%= f.label :brand %>:
  <%= f.text_field :brand %><br>
  <%= f.label :color %>:
  <%= f.text_field :color %><br>
  <%= f.label :price %>:
  <%= f.text_field :price %><br>
  <%= f.label :rating %>:
  <%= f.select :rating, (1..5) %><br>
  <%= f.label :comment %><br>
  <%= f.text_area :comment %><br>
  <%= f.label "Category" %>:
  <%= f.collection_select(:category_id, @categories, :id, :name, :prompt => true) %><br>
<%= f.submit %>
<% end %>
</div>

app/views/items/_items_table.html.erb
<table class="table table-hover table-dark">
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Brand</th>
    <th scope="col">Color</th>
    <th scope="col">Category</th>
    <th scope="col">Price</th>
    <th scope="col">Rating</th>
    <th scope="col">Comment</th>
  </tr>
  <tr>
    <% @items.each do |i| %>
  </tr>
  <tr>
  <td><%= i.name %></td>
  <td><%= i.brand %></td>
  <td><%= i.color %></td>
  <td><%= i.category.name %></td>
  <td><%= number_to_currency(i.price) %></td>
  <td><%= i.rating %></td>
  <td><%= i.comment %></td>
  </tr>
  <% end %>
</table>

app/views/items/edit.html.erb
<h3>Edit Item</h3>
<% if @item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@item.errors.count, "error") %>.
      Please fix and submit again.
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@kit, @item] do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br>
  <%= f.label :brand %>:
  <%= f.text_field :brand %><br>
  <%= f.label :color %>:
  <%= f.text_field :color %><br>
  <%= f.label :price %>:
  <%= f.text_field :price %><br>
  <%= f.label :rating %>:
  <%= f.select :rating, (1..5) %><br>
  <%= f.label :comment %><br>
  <%= f.text_area :comment %><br>
  <%= f.label "Category" %>:
  <%= f.collection_select(:category_id, @categories, :id, :name, :prompt => true) %><br>
<%= f.submit %>
<% end %>
<%= link_to "Go Back to Kits", kits_path %><br><br>

app/views/items/index.html.erb
<h1>All Items</h1>
<div>
  <h3>Filter items by:</h3>
  <%= form_tag("/items", method: "get") do %>
    <%= label_tag "Category" %>
    <%= select_tag "category", options_from_collection_for_select(@categories, "id", "name"), include_blank: true %>
    <%= select_tag "rating", options_for_select(1..5), include_blank: true %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>
<br>
<%= render "items_table" %>
<br>
<%= link_to "Go Back to Kits", kits_path %><br><br>

app/views/items/new.html.erb
<h3>Add a New Items</h3>
<%= render "form" %>

app/views/kits/index.html.erb
<br>
<br>
<div class="main">
<h3>Welcome <%= current_user.name %></h3>

<h4>You have a total of <%= pluralize(@kits.count, "kit") %></h4>

  <p>Please select a kit from below to see more details</p>
  <% @kits.each do |k| %>
  <%= link_to k.name, kit_path(k) %>
  <p>Description: <%= k.description%></p>
  <button id="button" class="js-more" data-id="<%= k.id %>">Preview Kit</button><br><br>

 <table class="table table-striped table-dark" id=kitItemsTable style="display: none;"></table>
    <script id="kitItemsTemplate" type="text/x-handlebars-template" >
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Brand</th>
        <th scope="col">Color</th>
      </tr>
      {{#each this}}
      <tr>
          <td>{{name}}</td>
          <td>{{brand}}</td>
          <td>{{color}}</td>
      </tr>
      {{/each}}
    </script>
  <% end %>
<%= link_to 'Add a New Kit', new_kit_path%><br><br>
<%= link_to 'Sign Out', signout_path, method: :delete %><br>
<div>
<p>Check out other users' items and ratings:</p>
  <button id="button" class="js-allItems" data-id="">See All Items</button>
  <button id="button" class="js-byRating" data-id="">By Rating</button>
  <button id="button" class="js-Category" data-id="">By Category</button><br><br>
</div>
<div>

<table  class="table table-hover table-dark" id="allItemsTable" style="display: none;"></table>
<script id="allItemsTemplate" type="text/x-handlebars-template">

  <tr>
    <th>Name</th>
    <th>Brand</th>
    <th>Color</th>
    <th>Rating</th>
    <th>Category</th>
    <th>Comment</th>
  </tr>
  {{#each this}}
  <tr>
      <td>{{name}}</td>
      <td>{{brand}}</td>
      <td>{{color}}</td>
      <td>{{rating}}</td>
      <td>{{category.name}}</td>
      <td>{{comment}}</td>
  </tr>
  {{/each}}
</script>
</div>
</div>

app/views/kits/new.html.erb
<% if @kit.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= pluralize(@kit.errors.count, "error") %>
      prohibited this glam kit from being saved:
    </h3>

    <ul>
    <% @kit.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1>Add a New Kit Form</h1>
<div class="form">
  <p>Fields marked with * are required. The GlamKit will not be created
    unless these fields are filled in.</p>
<%= form_for(@kit) do |f| %>
  <%= f.label :name %> * :
  <%= f.text_field :name %><br>
  <%= f.label :description %> * :
  <%= f.text_field :description %><br>

  <p>Please add your first item to the GlamKit. You can add more
     items after the kit has been created with the initial item.</p>
  <%= f.fields_for :items do |i| %>
    <%= i.label :name %> * :
    <%= i.text_field :name %><br>
    <%= i.label :brand %>:
    <%= i.text_field :brand %><br>
    <%= i.label :color %>:
    <%= i.text_field :color %><br>
    <%= i.label :price %>:
    <%= i.text_field :price %><br>
    <%= i.label :rating %>
    <%= i.select :rating, (1..5) %><br>
    <%= i.label :comment %><br>
    <%= i.text_area :comment %><br>
    <%= i.label "Category" %> * :
    <%= i.collection_select(:category_id, @categories, :id, :name, :prompt => true) %>
    <% end %>
  <%= f.submit %>
<% end %>
<br><br>
<%= link_to "Go Back to Kits", kits_path %><br><br>
</div>
<div id="kitResult">
  <h2 id="kitName"></h2>
  <h3 id="kitId"></h3>
  <p id="kitDescription"></p>
  <p id="itemName"></p>
  <p id="itemBrand"></p>
  <p id="itemColor"></p>
</div>

app/views/kits/show.html.erb
<div class="main">
<h1><%= @kit.name %></h1>
<h2><%= @kit.description %></h2>
<p><%= pluralize(@kit.items.count, "item")%> in this kit</p>
<table id="kitItems" class="table table-hover table-dark">
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Brand</th>
    <th scope="col">Color</th>
    <th scope="col">Category</th>
    <th scope="col">Price</th>
    <th scope="col">Rating</th>
    <th scope="col">Comment</th>
  </tr>

  <tr>
    <% @kit.items.each do |i| %>
  </tr>
  <tr>
    <td><%= i.name %></td>
    <td><%= i.brand %></td>
    <td><%= i.color %></td>
    <td><%= i.category.name %></td>
    <td><%= number_to_currency(i.price) %></td>
    <td><%= i.rating %></td>
    <td><%= i.comment%></td>
    <td><%= button_to "Edit", edit_kit_item_path(@kit, i),  method: :get%></td>
    <td><%= button_to "Delete", kit_item_path(@kit, i), :form => { :id => "dbutton" }, method: :delete, data: { confirm: "Are you sure?" }%></td>
  </tr>
  <% end %>
</table>
<br>

<script id="itemTemplate" type= "text/x-handlebars-template">
<tr>
    <td>{{name}}</td>
    <td>{{brand}}</td>
    <td>{{color}}</td>
    <td>{{category}}</td>
    <td>${{price}}</td>
    <td>{{rating}}</td>
    <td>{{comment}}</td>
    <td><form class="button_to" method="get" action="/kits/<%= @kit.id %>/items/{{id}}/edit"><input type="submit" value="Edit"></form></td>

    <td><form class="button_to" method="post" action="/kits/<%= @kit.id %>/items/{{id}}">
        <input type="hidden" name="_method" value="delete">
        <input class="destroy" type="submit" value="Delete">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      </form></td>
  </tr>
</script>


<h3>Add Another Item</h3>
<%= render partial: "/items/form" %>

<%= link_to "Delete Kit", kit_path(@kit), method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "Go Back to Kits", kits_path %><br><br>
</div>

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <div class="container">
    <p>Copyright &copy;GlamKit.com</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #6B2D5C;" >
  <a class="navbar-brand" href="/">Glam Kit</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/kits">My Glam Kits</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/contact">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/about">About</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlamKit</title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <br>
    <%= yield %>

  <%= render 'layouts/footer' %>

  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About GlamKit</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
   Nunc sed velit dignissim sodales ut eu sem integer. Nunc faucibus a pellentesque sit amet porttitor.
   Orci a scelerisque purus semper eget duis at tellus at. Sagittis id consectetur purus ut faucibus pulvinar elementum.
   Mattis aliquam faucibus purus in massa. Diam sit amet nisl suscipit. Diam in arcu cursus euismod quis viverra.
   Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Quis commodo odio aenean sed.
   Quam viverra orci sagittis eu volutpat odio. Sit amet risus nullam eget felis eget nunc.
   Curabitur vitae nunc sed velit dignissim sodales ut. Ultrices vitae auctor eu augue ut lectus arcu bibendum at.
 Scelerisque purus semper eget duis at tellus at urna. Scelerisque mauris pellentesque pulvinar pellentesque.
 Nisl condimentum id venenatis a condimentum vitae sapien.</p>

<p>Aliquam id diam maecenas ultricies mi. Massa massa ultricies mi quis hendrerit dolor magna.
  Sociis natoque penatibus et magnis dis. Viverra ipsum nunc aliquet bibendum.
  Lorem donec massa sapien faucibus et molestie. Posuere morbi leo urna molestie at elementum.
  Venenatis cras sed felis eget velit aliquet sagittis. Et sollicitudin ac orci phasellus.
  Proin libero nunc consequat interdum varius sit. Ut etiam sit amet nisl purus in.
  At urna condimentum mattis pellentesque id nibh tortor id. Vestibulum morbi blandit cursus risus at.
  Et tortor at risus viverra.</p>

app/views/static_pages/contact.html.erb
<div>

  <h1>Contact Us</h1>
  <p>Email Us</p>

</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<h1>Sign Up</h1>

<div>
<%= form_for(@user) do |f| %>

  <label>Name: </label>
  <%= f.text_field :name %><br>

  <label>Email: </label>
  <%= f.email_field :email %><br>

  <label>Password: </label>
  <%= f.password_field :password %><br>

  <%= f.submit %>
<% end %>
</div>

<%= link_to 'Home', '/' %><br>
<%= link_to 'Sign Up', new_user_path %><br>